### ISSUE TITLE
Unknown error when adding first server

### ISSUE THREAD

**Issue by SamuXzX** [siper/Youamp#140]
I just downloaded the app and once opened the app I saw the login screen. I tried connecting to my Nextcloud instance using the address provided by the Music app (https://cloud.samuelezappala.it/apps/music/subsonic) and creating an API password.
I tried both without and with "Use legacy auth" option enabled: when I tap on "Test" I receive a generic "Test error" toast; when I tap "Add" the app crashes and from that moment on it refuses to start again. Deleting user data resets the situation.

I don't know how to provide more information.

**Comment by siper** [comment]
Thanks for replay. I'll try to reproduce on my own instance, and give you feedback.

**Comment by siper** [comment]
I'll test it with my owncloud instance. I'll fix bug with certificates, please use 1.0.0-aplpha05 version to fix issue.
Instructions:
1. On Nextcloud open Apps, and install Music app
2. Go to Music -> Settings, and generate Password for API
3. On YouAMP enter server https://<you owncloud instance>/apps/music/subsonic/ <-- with ends slash
4. Username enter you nextcloud username
5. In password enter you password, which you generated in step 2
6. Set **Legacy auth to true**

**Comment by SamuXzX** [comment]
It works! Thank you.
I see that lots of basic functions are still in development, but the app is very well organized.
Maybe the need for the trailing slash should be fixed?

**Comment by siper** [comment]
Thanks for test. I'll improve server test function on first beta release.
