### ISSUE TITLE
Unable to login on Firestick TV

### ISSUE THREAD

**Issue by accforgithubtest** [siper/Youamp#198]
Hello there, this looks like a neat project and thank you creating this.

I was trying to set this up on the amazon firestick tv (4k version) and I am unable to login. I ee the fields for entering the name, url, user and password. However there is no login button, and there is no way to finish the set up.

Clicking next on the screen doesnt do anything either. 

Would be great to have this as a music listening app on the tv/soundbar as a subsonic client - so getting this issue fixed will be great to try it out.

**Comment by siper** [comment]
Hello. Thank you for feedback. Can you please add screenshot? It helps me understand the problem.

**Comment by siper** [comment]
I'm not planned create tv support on this app development stage, but I fix this issue and make it usable on tv.
