### ISSUE TITLE
Can not login on nextcloud / music app

### ISSUE THREAD

**Issue by wuppiwuppi** [siper/Youamp#201]
I run the latest nextcloud release on a local server with a letsencrypt https certificate. It has the music app enabled. 

I try to log in on that:
name: random
url: https://cloud.xxx.de/apps/music/subsonic
user / password is my regular pw, I also tried with user / api password

Result when pressing test: "failed". It does not tell me why. 
Pressing save does not solve it either. 

what is wrong?

**Comment by siper** [comment]
Hello, thanks for report. Please, see #140

**Comment by wuppiwuppi** [comment]
ok, so the legacy auth did it. Should the app try that by itself automatically?

Also, editing the server shows empty fields. 
Also: adding "https" disables the test and save button on the first try. removing the "s" and re-adding it solves it.

**Comment by siper** [comment]
> Also, editing the server shows empty fields.
Also: adding "https" disables the test and save button on the first try. removing the "s" and re-adding it solves it.

Thanks for reply. I'll fix it in next release.
