### ISSUE TITLE
Duration showing as +30 minutes

### ISSUE THREAD

**Issue by tiltshiftfocus** [siper/Youamp#232]
I like the simplicity of this app. I just updated from the beta. However, all of the music durations are still showing as 3x:xx instead of 0x:xx, which throws me off while trying to listen to a track (psychological).

I am using a Navidrome server, have not tried others. I am unsure if this is a locale issue or server issue. The screens below shows the difference of Youamp and Navidrome UI.

![Screenshot_20240814-192433_Youamp](https://github.com/user-attachments/assets/ff2da1d1-9e96-4985-b373-4d90eaceaa83)

![Screenshot_20240814-192903_Firefox](https://github.com/user-attachments/assets/6b56f380-aa2d-43ad-b0ec-6341024675c0)

**Comment by siper** [comment]
Hello, thanks for feedback. I can't reproduce this issue on my navidrome server.

**Comment by thelazyoxymoron** [comment]
I'm getting the same issue with my Navidrome server.
![Screenshot_20240825-212700_Youamp](https://github.com/user-attachments/assets/13d42858-9109-4835-a0cc-86cdbdaf96a7)
